/**
 * @file    nursery_controller.ino
 * @brief   Automated Commercial Micro-Climate Nursery controller (COMP50069, Scenario 2).
 * @author  M N M Shahmi (CB016484)
 *
 * @details
 * Hardware : ESP32, DHT22, LDR divider, potentiometer (manual vent position
 *            knob), 2 x servo vents, white grow LED (PWM), yellow (AUTO) /
 *            blue (MANUAL) / red (FAULT) LEDs, push-button, 128x64 I2C OLED.
 *
 * Modes    : AUTONOMOUS - closed-loop climate control using the priority hierarchy.
 *            MANUAL     - all automation bypassed, vents positioned by the
 *                         potentiometer (turn fully to lock vents open).
 *            FAULT      - a sensor failed; system holds a predefined safe posture
 *                         until the sensor recovers AND the operator acknowledges.
 *
 * Timing   : A 10 ms ESP32 hardware-timer interrupt increments a tick counter.
 *            loop() never calls delay(); each task runs when its tick interval
 *            has elapsed (cooperative scheduler).
 *
 * Libraries: Adafruit SSD1306, Adafruit GFX, DHT sensor library (Adafruit),
 *            Adafruit Unified Sensor. Works on ESP32 Arduino core 2.x and 3.x.
 */

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <DHT.h>
#include <esp_arduino_version.h>
#include "soc/gpio_reg.h"   // GPIO register addresses for register-level I/O

/* =====================================================================
 *  PIN MAP
 * ===================================================================== */
#define PIN_DHT          26   /**< DHT22 single-wire data line.            */
#define PIN_BUTTON        4   /**< Mode toggle, active low, internal pull. */
#define PIN_SERVO_A      18   /**< Vent A servo PWM.                       */
#define PIN_SERVO_B      19   /**< Vent B servo PWM.                       */
#define PIN_LED_WHITE    25   /**< Grow light actuator, PWM dimmed.        */
#define PIN_LED_BLUE     14   /**< MANUAL state indicator.                 */
#define PIN_LED_YELLOW   27   /**< AUTONOMOUS state indicator.             */
#define PIN_LED_RED      33   /**< FAULT annunciator, blink coded.         */
#define PIN_LDR          34   /**< LDR divider, ADC1 input only.           */
#define PIN_POT          35   /**< Manual vent knob, ADC1 input only.      */
#define PIN_I2C_SDA      21   /**< OLED I2C data.                          */
#define PIN_I2C_SCL      22   /**< OLED I2C clock.                         */

/* =====================================================================
 *  PWM (LEDC) CONFIGURATION
 *  Servos share LEDC timer 0 (channels 0/1, 50 Hz). The grow LED uses
 *  channel 4 (timer 2, 5 kHz) so the two frequencies never clash.
 * ===================================================================== */
#define CH_SERVO_A        0     /**< LEDC channel for vent A.              */
#define CH_SERVO_B        1     /**< LEDC channel for vent B.              */
#define CH_GROW           4     /**< LEDC channel for grow light.          */
#define SERVO_FREQ_HZ     50    /**< Standard hobby-servo frame rate.      */
#define SERVO_RES_BITS    16    /**< High resolution for smooth angles.    */
#define SERVO_PERIOD_US   20000 /**< 1 / 50 Hz.                            */
#define SERVO_MIN_US      500   /**< Pulse width at 0 degrees.             */
#define SERVO_MAX_US      2500  /**< Pulse width at 180 degrees.           */
#define VENT_CLOSED_DEG   0.0f  /**< Servo angle = vent fully closed.      */
#define VENT_OPEN_DEG     90.0f /**< Servo angle = vent fully open.        */
#define SERVO_STEP_DEG    1.0f  /**< Max movement per 20 ms (slew limit).  */
#define GROW_FREQ_HZ      5000  /**< Flicker-free LED dimming.             */
#define GROW_RES_BITS     8     /**< 0-255 duty.                           */

/* =====================================================================
 *  OLED
 * ===================================================================== */
#define OLED_WIDTH   128
#define OLED_HEIGHT  64
#define OLED_ADDR    0x3C

/* =====================================================================
 *  SCHEDULER (1 tick = 10 ms, generated by hardware timer)
 * ===================================================================== */
#define TICK_PERIOD_US    10000UL /**< Hardware timer period.              */
#define TICKS_PER_SECOND  100
#define TICKS_SERVO       2       /**< 20 ms  - servo slew step.           */
#define TICKS_CONTROL     10      /**< 100 ms - ADC read, mode + control.  */
#define TICKS_OLED        50      /**< 500 ms - redraw display.            */
#define TICKS_DHT         200     /**< 2 s    - DHT22 minimum read period. */
#define TICKS_STATUS      500     /**< 5 s    - serial status line.        */
#define BUTTON_DEBOUNCE_MS 250

/* =====================================================================
 *  SENSOR VALIDATION
 * ===================================================================== */
#define DHT_T_MIN        -40.0f  /**< DHT22 datasheet lower limit.        */
#define DHT_T_MAX         80.0f  /**< DHT22 datasheet upper limit.        */
#define DHT_FAULT_COUNT   2      /**< Consecutive bad reads before fault. */
#define LDR_RAIL_LOW      10     /**< ADC pinned at 0 V  -> short/open.   */
#define LDR_RAIL_HIGH     4085   /**< ADC pinned at 3.3V -> short/open.   */
#define LDR_FAULT_TICKS   300    /**< Rail must persist 3 s to trip.      */
#define LDR_BRIGHT_IS_HIGH true  /**< Flip if covering the LDR raises %.  */
#define ADC_SAMPLES       8      /**< Oversampling to reduce ADC noise.   */
#define POT_SNAP_PCT      3.0f   /**< Knob within 3 % of an end snaps to 0 / 100 %. */

/* =====================================================================
 *  CONTROL CONSTANTS
 * ===================================================================== */
#define VENT_DEADBAND_PCT   5.0f  /**< Demands below this = fully closed.  */
#define HUMID_MIN_VENT_PCT 25.0f  /**< Vent opening to break stagnant air. */
#define HEAT_LIGHT_CAP_PCT 30.0f  /**< Grow light cap during critical heat.*/
#define GROW_MIN_PCT       20.0f  /**< Lowest useful grow-light level.     */

/** @brief Operating modes. */
enum Mode : uint8_t { MODE_AUTO, MODE_MANUAL, MODE_FAULT };
static const char *MODE_NAMES[] = { "AUTO", "MANUAL", "FAULT" };

/** @brief Which rule of the priority hierarchy decided the vent position. */
enum Reason : uint8_t {
  R_WAIT, R_IDLE, R_COOLING, R_HUMIDITY, R_FROST_CAP,
  R_TOO_COLD, R_CRIT_HEAT, R_MANUAL, R_SAFE
};
static const char *REASON_NAMES[] = {
  "WAITING", "IDLE", "COOLING", "HUMIDITY", "FROST CAP",
  "TOO COLD", "CRIT HEAT", "MANUAL", "SAFE POSTURE"
};

/** @brief Tunable set-points (changeable at runtime over UART). */
struct Config {
  float tVent;          /**< Indoor temp where venting starts (C).          */
  float tBand;          /**< Rise above tVent that gives 100 % vent (C).    */
  float tCrit;          /**< Critical indoor heat -> vents 100 % (C).       */
  float tMinIn;         /**< Indoor too cold -> never vent (C).             */
  float tFrost;         /**< Outdoor at/below this = dangerous cold (C).    */
  float frostCapPct;    /**< Max vent opening when outdoor is frosty (%).   */
  float humMax;         /**< RH above this -> minimum air-circulation vent. */
  float safeVentPct;    /**< Vent position held in FAULT mode (%).          */
  float lightOnPct;     /**< Grow light turns ON below this light level.    */
  float lightOffPct;    /**< Grow light turns OFF above this light level.   */
  float manualTimeoutS; /**< Manual auto-resume time, 0 = never (s).        */
  float tOutdoor;       /**< Simulated outdoor temp, set over UART (C).     */
};
static Config cfg = { 26.0f, 6.0f, 35.0f, 16.0f, 5.0f, 20.0f,
                      85.0f, 30.0f, 35.0f, 45.0f, 600.0f, 20.0f };

/** @brief Live system state. */
struct State {
  Mode     mode = MODE_AUTO;
  Reason   reason = R_WAIT;
  float    tIn = NAN, hum = NAN;     /**< Last VALID DHT22 values.          */
  float    lightPct = 0;             /**< Light level 0-100 %.              */
  float    knobPct = 0;              /**< Manual vent knob 0-100 %.         */
  uint16_t ldrRaw = 0;
  uint8_t  dhtBad = 0;               /**< Consecutive bad DHT reads.        */
  uint16_t ldrRailTicks = 0;         /**< How long LDR has sat on a rail.   */
  bool     faultDht = false, faultLdr = false;
  bool     injectDht = false, injectLdr = false; /**< Test hooks (UART).   */
  float    ventDemand = 0;           /**< Combined vent demand 0-100 %.     */
  float    tgtA = VENT_CLOSED_DEG, tgtB = VENT_CLOSED_DEG;
  float    curA = VENT_CLOSED_DEG, curB = VENT_CLOSED_DEG;
  bool     growOn = false;
  float    growPct = 0;
  uint32_t manualStartTick = 0;
};
static State sys;

static Adafruit_SSD1306 oled(OLED_WIDTH, OLED_HEIGHT, &Wire, -1);
static bool gOledOk = false;
static DHT dht(PIN_DHT, DHT22);

static hw_timer_t *gTimer = nullptr;
static volatile uint32_t gTick = 0;          /**< Incremented every 10 ms.  */
static volatile bool     gButtonFlag = false;
static volatile uint32_t gButtonLastMs = 0;

/* =====================================================================
 *  INTERRUPT SERVICE ROUTINES
 * ===================================================================== */

/** @brief Hardware timer ISR: advances the scheduler tick. */
void IRAM_ATTR onTimerTick() { gTick++; }

/** @brief Button ISR (falling edge) with time-based debounce. */
void IRAM_ATTR onButton() {
  uint32_t ms = millis();
  if (ms - gButtonLastMs > BUTTON_DEBOUNCE_MS) {
    gButtonLastMs = ms;
    gButtonFlag = true;          // handled in loop(), ISR stays short
  }
}

/* =====================================================================
 *  REGISTER-LEVEL GPIO
 * ===================================================================== */

/**
 * @brief Set or clear an output pin by writing the GPIO W1TS/W1TC registers.
 * @param pin GPIO number (0-39).
 * @param on  true = HIGH, false = LOW.
 */
static inline void fastWrite(uint8_t pin, bool on) {
  if (pin < 32) REG_WRITE(on ? GPIO_OUT_W1TS_REG  : GPIO_OUT_W1TC_REG,  1UL << pin);
  else          REG_WRITE(on ? GPIO_OUT1_W1TS_REG : GPIO_OUT1_W1TC_REG, 1UL << (pin - 32));
}

/** @brief Read an input pin directly from the GPIO_IN registers. */
static inline bool fastRead(uint8_t pin) {
  if (pin < 32) return (REG_READ(GPIO_IN_REG)  >> pin) & 1UL;
  return              (REG_READ(GPIO_IN1_REG) >> (pin - 32)) & 1UL;
}

/* =====================================================================
 *  PWM HELPERS (hide the core 2.x / 3.x LEDC API difference)
 * ===================================================================== */

/** @brief Attach a pin to a fixed LEDC channel. */
static void pwmAttach(uint8_t pin, uint32_t freq, uint8_t bits, uint8_t ch) {
#if ESP_ARDUINO_VERSION_MAJOR >= 3
  ledcAttachChannel(pin, freq, bits, ch);
#else
  ledcSetup(ch, freq, bits);
  ledcAttachPin(pin, ch);
#endif
}

/** @brief Write a duty value to a pin/channel. */
static void pwmWrite(uint8_t pin, uint8_t ch, uint32_t duty) {
#if ESP_ARDUINO_VERSION_MAJOR >= 3
  (void)ch;  ledcWrite(pin, duty);
#else
  (void)pin; ledcWrite(ch, duty);
#endif
}

/** @brief Convert a servo angle to a 50 Hz pulse and output it. */
static void servoWriteDeg(uint8_t pin, uint8_t ch, float deg) {
  deg = constrain(deg, 0.0f, 180.0f);
  uint32_t us = SERVO_MIN_US + (uint32_t)(deg / 180.0f * (SERVO_MAX_US - SERVO_MIN_US));
  uint32_t duty = (uint32_t)((uint64_t)us * ((1UL << SERVO_RES_BITS) - 1) / SERVO_PERIOD_US);
  pwmWrite(pin, ch, duty);
}

/** @brief Convert a servo angle to vent opening percentage. */
static float ventPct(float deg) {
  return (deg - VENT_CLOSED_DEG) / (VENT_OPEN_DEG - VENT_CLOSED_DEG) * 100.0f;
}

/* =====================================================================
 *  SENSORS
 * ===================================================================== */

/** @brief Oversampled ADC read (averages ADC_SAMPLES conversions). */
static uint16_t readAdcAvg(uint8_t pin) {
  uint32_t sum = 0;
  for (uint8_t i = 0; i < ADC_SAMPLES; i++) sum += analogRead(pin);
  return (uint16_t)(sum / ADC_SAMPLES);
}

/**
 * @brief Read and validate the DHT22 (every 2 s).
 * A reading is rejected if it is NaN or outside the datasheet range.
 * Only validated values are stored; the fault trips after DHT_FAULT_COUNT
 * consecutive bad reads so one checksum glitch cannot shut the system down.
 */
static void readDht() {
  float t = dht.readTemperature();
  float h = dht.readHumidity();
  bool ok = !sys.injectDht && !isnan(t) && !isnan(h) &&
            t >= DHT_T_MIN && t <= DHT_T_MAX && h >= 0.0f && h <= 100.0f;
  if (ok) {
    sys.tIn = t; sys.hum = h; sys.dhtBad = 0;
  } else if (sys.dhtBad < 255) {
    sys.dhtBad++;
    Serial.printf("[DHT] invalid reading (%u in a row)\n", sys.dhtBad);
  }
  sys.faultDht = sys.dhtBad >= DHT_FAULT_COUNT;
}

/**
 * @brief Read LDR and potentiometer (every 100 ms).
 * LDR: converted to 0-100 % light; a reading stuck on either ADC rail for
 * 3 s means the divider is open/shorted -> LDR fault.
 * Pot: scaled to a 0-100 % manual vent position; the last 3 % at each end
 * snaps to fully closed / fully open so "locked open" is easy to reach.
 */
static void readAnalogSensors() {
  uint16_t raw = readAdcAvg(PIN_LDR);
  sys.ldrRaw = raw;
  bool onRail = (raw <= LDR_RAIL_LOW) || (raw >= LDR_RAIL_HIGH);
  if (onRail) { if (sys.ldrRailTicks < 60000) sys.ldrRailTicks += TICKS_CONTROL; }
  else          sys.ldrRailTicks = 0;
  sys.faultLdr = sys.injectLdr || (sys.ldrRailTicks >= LDR_FAULT_TICKS);

  float pct = raw * 100.0f / 4095.0f;
  sys.lightPct = LDR_BRIGHT_IS_HIGH ? pct : 100.0f - pct;

  float knob = readAdcAvg(PIN_POT) * 100.0f / 4095.0f;
  if (knob < POT_SNAP_PCT)                 knob = 0.0f;
  else if (knob > 100.0f - POT_SNAP_PCT)   knob = 100.0f;
  sys.knobPct = knob;
}

/* =====================================================================
 *  MODE MANAGEMENT
 * ===================================================================== */

/** @brief Human-readable name of the failed sensor(s). */
static const char *faultName() {
  if (sys.faultDht && sys.faultLdr) return "DHT22+LDR";
  if (sys.faultDht) return "DHT22";
  if (sys.faultLdr) return "LDR";
  return "none";
}

/** @brief Switch mode and log the transition. */
static void enterMode(Mode m, const char *why) {
  if (m == sys.mode) return;
  sys.mode = m;
  if (m == MODE_MANUAL) sys.manualStartTick = gTick;
  Serial.printf("[MODE] -> %s (%s)\n", MODE_NAMES[m], why);
}

/** @brief Leave FAULT only if every sensor is healthy again. */
static void tryClearFault(const char *src) {
  if (sys.faultDht || sys.faultLdr)
    Serial.printf("[FAULT] cannot clear - %s still failed\n", faultName());
  else
    enterMode(MODE_AUTO, src);
}

/** @brief Button press: AUTO <-> MANUAL, or acknowledge a cleared fault. */
static void handleButton() {
  switch (sys.mode) {
    case MODE_AUTO:   enterMode(MODE_MANUAL, "button"); break;
    case MODE_MANUAL: enterMode(MODE_AUTO,   "button"); break;
    case MODE_FAULT:  tryClearFault("fault acknowledged by button"); break;
  }
}

/**
 * @brief Automatic transitions: sensor fault (highest priority, from any mode)
 * and the scheduled manual-override timeout.
 */
static void updateMode(uint32_t now) {
  if ((sys.faultDht || sys.faultLdr) && sys.mode != MODE_FAULT) {
    Serial.printf("[FAULT] sensor failure: %s\n", faultName());
    enterMode(MODE_FAULT, "sensor fault");
  }
  if (sys.mode == MODE_MANUAL && cfg.manualTimeoutS > 0 &&
      (now - sys.manualStartTick) >= (uint32_t)(cfg.manualTimeoutS * TICKS_PER_SECOND)) {
    enterMode(MODE_AUTO, "manual timeout elapsed");
  }
}

/* =====================================================================
 *  CONTROL LOGIC - THE PRIORITY HIERARCHY
 * ===================================================================== */

/**
 * @brief Compute vent demand (0-100 %) in AUTONOMOUS mode.
 *
 * Rules are checked from highest to lowest priority:
 *  1. Critical indoor heat  -> 100 % (heat damage is fast and irreversible,
 *                              so it outranks outdoor cold).
 *  2. Indoor already cold   -> 0 %   (venting would only cool it further).
 *  3. Cooling demand        -> proportional to how far above tVent we are.
 *  4. High humidity         -> at least HUMID_MIN_VENT_PCT to move stagnant air.
 *  5. Outdoor frost         -> cap the result of 3/4 at frostCapPct so cold
 *                              air enters slowly instead of shocking the crop.
 */
static float computeVentDemand(Reason &why) {
  if (isnan(sys.tIn))        { why = R_WAIT;      return 0.0f; }
  if (sys.tIn >= cfg.tCrit)  { why = R_CRIT_HEAT; return 100.0f; }
  if (sys.tIn <= cfg.tMinIn) { why = R_TOO_COLD;  return 0.0f; }

  float d = 0.0f;
  why = R_IDLE;
  if (sys.tIn > cfg.tVent) {
    d = (sys.tIn - cfg.tVent) / cfg.tBand * 100.0f;
    why = R_COOLING;
  }
  if (!isnan(sys.hum) && sys.hum > cfg.humMax && d < HUMID_MIN_VENT_PCT) {
    d = HUMID_MIN_VENT_PCT;
    why = R_HUMIDITY;
  }
  if (cfg.tOutdoor <= cfg.tFrost && d > cfg.frostCapPct) {
    d = cfg.frostCapPct;
    why = R_FROST_CAP;
  }
  d = constrain(d, 0.0f, 100.0f);
  if (d < VENT_DEADBAND_PCT) d = 0.0f;
  return d;
}

/**
 * @brief Grow-light level with hysteresis (ON below lightOnPct, OFF above
 * lightOffPct) and brightness proportional to the light deficit.
 * During critical heat the light is capped because LEDs add heat.
 */
static float computeGrowPct() {
  if (!sys.growOn && sys.lightPct < cfg.lightOnPct)       sys.growOn = true;
  else if (sys.growOn && sys.lightPct > cfg.lightOffPct)  sys.growOn = false;
  if (!sys.growOn || cfg.lightOffPct < 1.0f) return 0.0f;

  float pct = (cfg.lightOffPct - sys.lightPct) / cfg.lightOffPct * 100.0f;
  pct = constrain(pct, GROW_MIN_PCT, 100.0f);
  if (!isnan(sys.tIn) && sys.tIn >= cfg.tCrit) pct = fminf(pct, HEAT_LIGHT_CAP_PCT);
  return pct;
}

/**
 * @brief Staged venting: vent A covers demand 0-50 %, vent B joins for
 * 50-100 %. Small corrections use one vent, big heat loads use both.
 */
static void setVentTargets(float demand) {
  float a = fminf(demand * 2.0f, 100.0f);
  float b = fmaxf(demand * 2.0f - 100.0f, 0.0f);
  sys.tgtA = VENT_CLOSED_DEG + a / 100.0f * (VENT_OPEN_DEG - VENT_CLOSED_DEG);
  sys.tgtB = VENT_CLOSED_DEG + b / 100.0f * (VENT_OPEN_DEG - VENT_CLOSED_DEG);
}

/** @brief Decide actuator outputs for the current mode (every 100 ms). */
static void runControl() {
  switch (sys.mode) {
    case MODE_AUTO:
      sys.ventDemand = computeVentDemand(sys.reason);
      sys.growPct = computeGrowPct();
      break;
    case MODE_MANUAL:                 // automation bypassed, knob drives vents
      sys.ventDemand = sys.knobPct;
      sys.reason = R_MANUAL;
      sys.growPct = 0.0f; sys.growOn = false;
      break;
    case MODE_FAULT:                  // predefined safe physical posture
      sys.ventDemand = cfg.safeVentPct;
      sys.reason = R_SAFE;
      sys.growPct = 0.0f; sys.growOn = false;
      break;
  }
  if (sys.mode == MODE_MANUAL) {
    // Both vents follow the knob together - no staging in manual.
    float deg = VENT_CLOSED_DEG + sys.knobPct / 100.0f * (VENT_OPEN_DEG - VENT_CLOSED_DEG);
    sys.tgtA = deg;
    sys.tgtB = deg;
  } else {
    setVentTargets(sys.ventDemand);
  }
  pwmWrite(PIN_LED_WHITE, CH_GROW, (uint32_t)(sys.growPct * 255.0f / 100.0f));
}

/** @brief Move a value one slew step toward its target. */
static float stepToward(float cur, float tgt) {
  if (fabsf(tgt - cur) <= SERVO_STEP_DEG) return tgt;
  return cur + (tgt > cur ? SERVO_STEP_DEG : -SERVO_STEP_DEG);
}

/**
 * @brief Slew-limited servo update (every 20 ms). Moving 1 degree per step
 * avoids current spikes that can brown-out the ESP32.
 */
static void updateServos() {
  float a = stepToward(sys.curA, sys.tgtA);
  float b = stepToward(sys.curB, sys.tgtB);
  if (a != sys.curA) { sys.curA = a; servoWriteDeg(PIN_SERVO_A, CH_SERVO_A, a); }
  if (b != sys.curB) { sys.curB = b; servoWriteDeg(PIN_SERVO_B, CH_SERVO_B, b); }
}

/**
 * @brief Mode LEDs: yellow = AUTO, blue = MANUAL, red = FAULT.
 * Red LED blink code in FAULT: 1 blink = DHT22, 2 = LDR, 3 = both,
 * solid = sensors recovered, waiting for acknowledgement.
 */
static void updateIndicators(uint32_t now) {
  fastWrite(PIN_LED_YELLOW, sys.mode == MODE_AUTO);
  fastWrite(PIN_LED_BLUE,   sys.mode == MODE_MANUAL);
  bool red = false;
  if (sys.mode == MODE_FAULT) {
    uint8_t code = (sys.faultDht ? 1 : 0) + (sys.faultLdr ? 2 : 0);
    if (code == 0) red = true;
    else {
      uint32_t phase = (now / 10) % 20;       // 100 ms steps, 2 s cycle
      red = (phase < code * 2u) && (phase % 2 == 0);
    }
  }
  fastWrite(PIN_LED_RED, red);
}

/* =====================================================================
 *  OLED
 * ===================================================================== */

/** @brief Format a float, or "--.-" if it is not valid yet. */
static void fmtVal(char *buf, size_t n, float v) {
  if (isnan(v)) snprintf(buf, n, "--.-");
  else          snprintf(buf, n, "%.1f", v);
}

/** @brief Draw an inverted title bar. */
static void drawHeader(const char *text) {
  oled.fillRect(0, 0, OLED_WIDTH, 10, SSD1306_WHITE);
  oled.setTextColor(SSD1306_BLACK);
  oled.setCursor(2, 1);
  oled.print(text);
  oled.setTextColor(SSD1306_WHITE);
  oled.setCursor(0, 13);
}

/** @brief Redraw the screen for the current mode (every 500 ms). */
static void drawOled(uint32_t now) {
  if (!gOledOk) return;
  char t[8], h[8], hdr[24];
  fmtVal(t, sizeof t, sys.tIn);
  fmtVal(h, sizeof h, sys.hum);
  oled.clearDisplay();
  oled.setTextSize(1);

  switch (sys.mode) {
    case MODE_AUTO:
      snprintf(hdr, sizeof hdr, "AUTO: %s", REASON_NAMES[sys.reason]);
      drawHeader(hdr);
      oled.printf("In %sC  RH %s%%\n", t, h);
      oled.printf("Out %.1fC  Lt %.0f%%\n", cfg.tOutdoor, sys.lightPct);
      oled.printf("Grow light %.0f%%\n", sys.growPct);
      oled.printf("Vent A %.0f%%  B %.0f%%\n", ventPct(sys.curA), ventPct(sys.curB));
      oled.printf("Set %.1f Crit %.1f\n", cfg.tVent, cfg.tCrit);
      oled.print("BTN: manual override");
      break;

    case MODE_MANUAL: {
      drawHeader("MANUAL OVERRIDE");
      oled.println("Automation SUSPENDED");
      oled.printf("Knob sets vents %.0f%%\n", sys.knobPct);
      oled.printf("Vent A %.0f%%  B %.0f%%\n", ventPct(sys.curA), ventPct(sys.curB));
      oled.printf("In %sC  RH %s%%\n", t, h);
      if (cfg.manualTimeoutS > 0) {
        uint32_t elapsed = (now - sys.manualStartTick) / TICKS_PER_SECOND;
        uint32_t left = (elapsed < cfg.manualTimeoutS) ? (uint32_t)cfg.manualTimeoutS - elapsed : 0;
        oled.printf("Auto resume %02lu:%02lu\n", (unsigned long)(left / 60), (unsigned long)(left % 60));
      } else {
        oled.println("No auto-resume");
      }
      oled.print("BTN: back to AUTO");
      break;
    }

    case MODE_FAULT: {
      bool stillFailed = sys.faultDht || sys.faultLdr;
      drawHeader("!! SENSOR FAULT !!");
      oled.printf("Failed: %s\n", stillFailed ? faultName() : "cleared");
      oled.println("Safe posture active");
      oled.printf("Vent %.0f%%  Grow OFF\n", cfg.safeVentPct);
      if (!sys.faultDht)      oled.printf("In %sC  RH %s%%\n", t, h);
      else if (!sys.faultLdr) oled.printf("Light %.0f%%\n", sys.lightPct);
      else                    oled.println("No valid readings");
      if (stillFailed) { oled.println("Check sensor wiring"); oled.print("Operator required"); }
      else             { oled.println("Sensor OK now");       oled.print("Press BTN to resume"); }
      break;
    }
  }
  oled.display();
}

/* =====================================================================
 *  UART - STATUS OUTPUT AND CONFIGURATION INPUT
 * ===================================================================== */

/** @brief Runtime-tunable parameters for the "set" command. */
struct ParamDef { const char *key; float *val; float lo, hi; const char *desc; };
static ParamDef PARAMS[] = {
  { "vent",  &cfg.tVent,          10,   45, "indoor temp where venting starts (C)" },
  { "band",  &cfg.tBand,           1,   20, "rise above vent temp for 100% open (C)" },
  { "crit",  &cfg.tCrit,          20,   50, "critical heat, full vent (C)" },
  { "min",   &cfg.tMinIn,          0,   30, "indoor too cold, never vent (C)" },
  { "frost", &cfg.tFrost,        -10,   15, "outdoor frost limit (C)" },
  { "fcap",  &cfg.frostCapPct,     0,  100, "max vent when frosty (%)" },
  { "hum",   &cfg.humMax,         40,  100, "humidity for air-circulation vent (%)" },
  { "safe",  &cfg.safeVentPct,     0,  100, "FAULT safe vent position (%)" },
  { "lon",   &cfg.lightOnPct,      0,  100, "grow light ON below (%)" },
  { "loff",  &cfg.lightOffPct,     0,  100, "grow light OFF above (%)" },
  { "mto",   &cfg.manualTimeoutS,  0, 7200, "manual auto-resume, 0 = off (s)" },
  { "out",   &cfg.tOutdoor,      -20,   50, "simulated outdoor temperature (C)" },
};
static const size_t N_PARAMS = sizeof(PARAMS) / sizeof(PARAMS[0]);

/** @brief Print the command list and current parameter values. */
static void printHelp() {
  Serial.println(F("\n=== Nursery controller commands ==="));
  Serial.println(F(" help | status | manual | auto | ack"));
  Serial.println(F(" set <param> <value>"));
  Serial.println(F(" inject dht | inject ldr | inject off   (fault test hooks)"));
  for (size_t i = 0; i < N_PARAMS; i++)
    Serial.printf("   %-5s = %7.1f  %s\n", PARAMS[i].key, *PARAMS[i].val, PARAMS[i].desc);
}

/** @brief One-line live status (every 5 s and on "status"). */
static void printStatusLine() {
  char t[8], h[8];
  fmtVal(t, sizeof t, sys.tIn);
  fmtVal(h, sizeof h, sys.hum);
  Serial.printf("[%s] In=%sC RH=%s%% Out=%.1fC Light=%.0f%% (raw %u) Knob=%.0f%% Grow=%.0f%% "
                "VentA=%.0f%% VentB=%.0f%% Why=%s Fault=%s\n",
                MODE_NAMES[sys.mode], t, h, cfg.tOutdoor, sys.lightPct, sys.ldrRaw, sys.knobPct,
                sys.growPct, ventPct(sys.curA), ventPct(sys.curB),
                REASON_NAMES[sys.reason], faultName());
}

/** @brief Handle "set <param> <value>". */
static void setParam(const char *key, const char *valStr) {
  if (!key || !valStr) { Serial.println(F("usage: set <param> <value>")); return; }
  char *end;
  float v = strtof(valStr, &end);
  if (end == valStr) { Serial.println(F("value is not a number")); return; }
  for (size_t i = 0; i < N_PARAMS; i++) {
    if (strcmp(key, PARAMS[i].key) == 0) {
      if (v < PARAMS[i].lo || v > PARAMS[i].hi) {
        Serial.printf("out of range (%.0f..%.0f)\n", PARAMS[i].lo, PARAMS[i].hi);
        return;
      }
      *PARAMS[i].val = v;
      Serial.printf("[CFG] %s = %.1f\n", key, v);
      if (cfg.tCrit <= cfg.tVent)        Serial.println(F("[CFG] warning: crit should be above vent"));
      if (cfg.lightOffPct <= cfg.lightOnPct) Serial.println(F("[CFG] warning: loff should be above lon"));
      return;
    }
  }
  Serial.println(F("unknown parameter - type help"));
}

/** @brief Parse and execute one command line. */
static void processCommand(char *line) {
  for (char *p = line; *p; ++p) *p = tolower(*p);
  char *cmd = strtok(line, " ");
  if (!cmd) return;
  char *a1 = strtok(nullptr, " ");
  char *a2 = strtok(nullptr, " ");

  if      (!strcmp(cmd, "help"))   printHelp();
  else if (!strcmp(cmd, "status")) printStatusLine();
  else if (!strcmp(cmd, "manual")) {
    if (sys.mode == MODE_FAULT) Serial.println(F("clear the fault first (ack)"));
    else enterMode(MODE_MANUAL, "serial command");
  }
  else if (!strcmp(cmd, "auto")) {
    if (sys.mode == MODE_FAULT) Serial.println(F("clear the fault first (ack)"));
    else enterMode(MODE_AUTO, "serial command");
  }
  else if (!strcmp(cmd, "ack")) {
    if (sys.mode == MODE_FAULT) tryClearFault("fault acknowledged by serial");
    else Serial.println(F("no active fault"));
  }
  else if (!strcmp(cmd, "set")) setParam(a1, a2);
  else if (!strcmp(cmd, "inject") && a1) {
    if      (!strcmp(a1, "dht")) sys.injectDht = true;
    else if (!strcmp(a1, "ldr")) sys.injectLdr = true;
    else if (!strcmp(a1, "off")) { sys.injectDht = false; sys.injectLdr = false; }
    Serial.printf("[TEST] inject dht=%d ldr=%d\n", sys.injectDht, sys.injectLdr);
  }
  else Serial.println(F("unknown command - type help"));
}

/** @brief Non-blocking serial line reader. */
static void pollSerial() {
  static char buf[64];
  static uint8_t len = 0;
  while (Serial.available()) {
    char c = (char)Serial.read();
    if (c == '\r' || c == '\n') {
      if (len) { buf[len] = '\0'; processCommand(buf); len = 0; }
    } else if (len < sizeof(buf) - 1) {
      buf[len++] = c;
    }
  }
}

/* =====================================================================
 *  SETUP / LOOP
 * ===================================================================== */

/** @brief Hardware timer: 10 ms periodic interrupt. */
static void startTickTimer() {
#if ESP_ARDUINO_VERSION_MAJOR >= 3
  gTimer = timerBegin(1000000);                    // 1 MHz timer clock
  timerAttachInterrupt(gTimer, &onTimerTick);
  timerAlarm(gTimer, TICK_PERIOD_US, true, 0);     // auto-reload
#else
  gTimer = timerBegin(0, 80, true);                // 80 MHz / 80 = 1 MHz
  timerAttachInterrupt(gTimer, &onTimerTick, true);
  timerAlarmWrite(gTimer, TICK_PERIOD_US, true);
  timerAlarmEnable(gTimer);
#endif
}

void setup() {
  Serial.begin(115200);

  pinMode(PIN_LED_BLUE,   OUTPUT);
  pinMode(PIN_LED_YELLOW, OUTPUT);
  pinMode(PIN_LED_RED,    OUTPUT);
  pinMode(PIN_BUTTON,     INPUT_PULLUP);
  pinMode(PIN_LDR,        INPUT);
  pinMode(PIN_POT,        INPUT);
  attachInterrupt(digitalPinToInterrupt(PIN_BUTTON), onButton, FALLING);

  analogReadResolution(12);

  pwmAttach(PIN_SERVO_A,   SERVO_FREQ_HZ, SERVO_RES_BITS, CH_SERVO_A);
  pwmAttach(PIN_SERVO_B,   SERVO_FREQ_HZ, SERVO_RES_BITS, CH_SERVO_B);
  pwmAttach(PIN_LED_WHITE, GROW_FREQ_HZ,  GROW_RES_BITS,  CH_GROW);
  servoWriteDeg(PIN_SERVO_A, CH_SERVO_A, VENT_CLOSED_DEG);
  servoWriteDeg(PIN_SERVO_B, CH_SERVO_B, VENT_CLOSED_DEG);
  pwmWrite(PIN_LED_WHITE, CH_GROW, 0);

  Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);
  Wire.setClock(400000);                           // faster redraw (~25 ms)
  gOledOk = oled.begin(SSD1306_SWITCHCAPVCC, OLED_ADDR);
  if (gOledOk) {
    oled.clearDisplay();
    oled.setTextColor(SSD1306_WHITE);
    oled.setTextSize(1);
    oled.setCursor(0, 20);
    oled.println("Micro-Climate Nursery");
    oled.println("Starting...");
    oled.display();
  } else {
    Serial.println(F("[OLED] not found at 0x3C - check SDA/SCL wiring"));
  }

  dht.begin();
  startTickTimer();
  printHelp();
  Serial.println(F("[MODE] -> AUTO (power on)"));
}

void loop() {
  static uint32_t tServo = 0, tControl = 0, tDht = 0, tOled = 0, tStatus = 0;

  pollSerial();
  if (gButtonFlag) { gButtonFlag = false; handleButton(); }

  uint32_t now = gTick;
  if (now - tServo   >= TICKS_SERVO)   { tServo = now;   updateServos(); }
  if (now - tDht     >= TICKS_DHT)     { tDht = now;     readDht(); }
  if (now - tControl >= TICKS_CONTROL) {
    tControl = now;
    readAnalogSensors();
    updateMode(now);
    runControl();
    updateIndicators(now);
  }
  if (now - tOled    >= TICKS_OLED)    { tOled = now;    drawOled(now); }
  if (now - tStatus  >= TICKS_STATUS)  { tStatus = now;  printStatusLine(); }
}
